package com.sist.member;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.util.Random;

public class InsertMember {
	public static void main(String[] args) {
		String []firstName = {"±è","ÀÌ","¹Ú","ÃÖ",
				"È«","È²º¸","³²±Ã","À±","³ë","ÀÓ",
				"À¯","Á¤",
				"ÇÑ","¼­","ÅÂ","Â÷","¿À","½Å","±Ç","¼Û","¾È","¹®","°í","¾ç","Á¶","Á¤","Àå","°­","¹è","¹é","Çã"
		};
		
		String name = "°¡°¢AB°£CD°¤°¥°¦°§EFGHI°¨°©°ª°«°¬°­°®°¯J°°°±°²"
				+ "°³°´KL°µMNO°¶PQRSTUV°·°¸W°¹°º°»XYZabc"
				+ "°¼°½de°¾fgh°¿ijklmnopqr°Às°Átuvwxy"
				+ "°Âz‚°Ãƒ„…°Ä†‡ˆ‰Š‹ŒŽ‘’“”•–—˜"
				+ "°Å°Æ™š°Ç›œ°È°É°ÊžŸ ¡¢°Ë°Ì£°Í°Î°Ï°Ð¤¥°Ñ°Ò°Ó"
				+ "°Ô¦§¨°Õ©ª«°Ö¬­®¯°±²°×°Ø³°Ù°Ú°Û´µ¶·¸¹"
				+ "°Ü°Ý°Þº°ß»¼°à°á½¾¿ÀÁÂÃ°â°ãÄ°ä°å°æÅÆÇ°çÈÉ"
				+ "°èÊËÌ°éÍÎÏ°êÐÑÒÓÔÕÖ×°ëØ°ìÙÚÛÜÝÞßà"
				+ "°í°îáâ°ïãä°ð°ñå°òæ°óçè°ô°õ°öé°÷ê°ø°ùëìíîï"
				+ "°ú°ûðñ°üòóô°ýõ°þö÷øùú±¡±¢û±£ü±¤ýþ‚A‚B‚C‚D"
				+ "±¥‚E‚F‚G±¦‚H‚I‚J±§‚K‚L‚M‚N‚O‚P‚Q‚R±¨‚S‚T±©±ª‚U‚V‚W‚X‚Y‚Z"
				+ "±«±¬‚a‚b±­‚c‚d‚e±®‚f‚g‚h‚i‚j‚k‚l±¯±°‚m±±‚n±²‚o‚p‚q‚r‚s‚t"
				+ "±³‚u‚v‚w±´‚x‚y‚z±µ‚‚‚‚ƒ‚„‚…‚†‚‡‚ˆ±¶‚‰±·‚Š‚‹‚Œ‚‚Ž‚‚‚‘"
				+ "±¸±¹‚’‚“±º‚”‚•±»±¼±½±¾‚–‚—‚˜‚™±¿±À±Á‚š±Â‚›±Ã±Ä‚œ‚‚ž‚Ÿ‚ "
				+ "±Å±Æ‚¡‚¢±Ç‚£‚¤‚¥±È‚¦‚§‚¨‚©‚ª‚«‚¬‚­‚®‚¯‚°±É±Ê‚±‚²‚³‚´‚µ‚¶"
				+ "±Ë‚·‚¸‚¹‚º‚»‚¼‚½‚¾‚¿‚À‚Á‚Â‚Ã‚Ä‚Å‚Æ‚Ç‚È±Ì‚É‚Ê‚Ë‚Ì‚Í‚Î‚Ï‚Ð"
				+ "±Í±Î‚Ñ‚Ò±Ï‚Ó‚Ô‚Õ±Ð‚Ö‚×‚Ø‚Ù‚Ú‚Û‚Ü±Ñ±Ò‚Ý±Ó‚Þ‚ß‚à‚á‚â‚ã‚ä‚å"
				+ "±Ô‚æ‚ç‚è±Õ‚é‚ê‚ë±Ö‚ì‚í‚î‚ï‚ð‚ñ‚ò‚ó‚ô‚õ‚ö‚÷‚ø‚ù‚ú‚û‚ü‚ý‚þ"
				+ "±×±ØƒAƒB±ÙƒCƒD±Ú±Û±ÜƒEƒFƒGƒHƒIƒJ±Ý±ÞƒK±ßƒL±àƒMƒNƒOƒPƒQƒR"
				+ "±áƒSƒTƒUƒVƒWƒXƒYƒZƒaƒbƒcƒdƒeƒfƒgƒhƒiƒjƒkƒlƒmƒnƒoƒpƒqƒrƒs"
				+ "±â±ãƒtƒu±äƒvƒw±å±æƒx±çƒyƒzƒƒ‚ƒƒ±è±éƒ„±êƒ…±ë±ìƒ†ƒ‡ƒˆ±íƒ‰"
				+ "±î±ï±ðƒŠ±ñƒ‹ƒŒƒ±òƒŽ±óƒƒƒ‘ƒ’ƒ“±ô±õƒ”±ö±÷±øƒ•ƒ–ƒ—±ùƒ˜ƒ™"
				+ "±ú±ûƒšƒ›±üƒœƒƒž±ýƒŸƒ ƒ¡ƒ¢ƒ£ƒ¤ƒ¥±þ²¡ƒ¦²¢²£²¤ƒ§ƒ¨ƒ©ƒªƒ«ƒ¬"
				+ "²¥²¦ƒ­ƒ®ƒ¯ƒ°ƒ±ƒ²²§ƒ³ƒ´ƒµƒ¶ƒ·ƒ¸ƒ¹ƒºƒ»ƒ¼ƒ½ƒ¾ƒ¿ƒÀƒÁƒÂƒÃƒÄƒÅ"
				+ "ƒÆƒÇƒÈƒÉƒÊƒËƒÌƒÍƒÎƒÏƒÐƒÑƒÒƒÓƒÔƒÕƒÖƒ×ƒØƒÙƒÚƒÛƒÜƒÝƒÞƒßƒàƒá"
				+ "²¨²©²ªƒâ²«ƒãƒäƒå²¬ƒæƒçƒèƒéƒêƒëƒì²­²®ƒí²¯²°²±ƒîƒïƒðƒñƒòƒó"
				+ "²²²³ƒôƒõ²´ƒöƒ÷ƒøƒùƒúƒûƒüƒýƒþ„A„B²µ„C„D²¶„E²·„F„G„H„I„J„K"
				+ "²¸„L„M„N²¹„O„P„Q²º„R„S„T„U„V„W„X„Y„Z„a²»²¼„b„c„d„e²½„f„g"
				+ "²¾„h„i„j„k„l„m„n„o„p„q„r„s„t„u„v„w„x„y„z„„‚„ƒ„„„…„†„‡„ˆ"
				+ "²¿²À„‰„Š²Á„‹²Â„Œ²Ã„„Ž„„„‘„’„“²Ä²Å„”²Æ„•²Ç²È²É„–„—„˜„™"
				+ "²Ê²Ë„š„›„œ„„ž„Ÿ²Ì„ „¡„¢„£„¤„¥„¦„§„¨„©„ª²Í²Î„«„¬„­„®„¯„°"
				+ "²Ï²Ð„±„²„³„´„µ„¶„·„¸„¹„º„»„¼„½„¾„¿„À„Á„Â„Ã²Ñ„Ä„Å„Æ„Ç„È„É"
				+ "²Ò„Ê„Ë„Ì²Ó„Í„Î„Ï²Ô„Ð„Ñ„Ò„Ó„Ô„Õ„Ö²Õ²Ö„×„Ø„Ù²×„Ú„Û„Ü„Ý„Þ„ß"
				+ "²Ø„à„á„â„ã„ä„å„æ„ç„è„é„ê„ë„ì„í„î„ï„ð„ñ„ò„ó„ô„õ„ö„÷„ø„ù„ú"
				+ "²Ù²Ú„û„ü²Û„ý„þ…A²Ü…B…C…D…E…F…G²Ý²Þ²ß…H²à…I²á²â…J…K…L…M…N"
				+ "²ã…O…P…Q…R…S…T…U²ä…V…W…X…Y…Z…a…b…c…d…e…f²å²æ…g…h…i…j…k…l"
				+ "²ç²è…m…n²é…o…p…q²ê…r…s…t…u…v…w…x²ë²ì…y…z²í……‚…ƒ…„………†…‡"
				+ "²î…ˆ…‰…Š²ï…‹…Œ…²ð…Ž………‘…’…“…”²ñ²ò…•…–…—…˜…™…š…›…œ……ž"
				+ "²ó…Ÿ… …¡…¢…£…¤…¥…¦…§…¨…©…ª…«…¬…­…®…¯…°…±…²…³…´…µ…¶…·…¸…¹"
				+ "²ô²õ…º…»²ö…¼²÷…½²ø…¾²ù…¿…À…Á…Â²ú²û²ü…Ã²ý…Ä²þ…Å…Æ…Ç³¡…È…É"
				+ "…Ê…Ë…Ì…Í…Î…Ï…Ð…Ñ…Ò…Ó…Ô…Õ…Ö…×…Ø…Ù…Ú…Û…Ü…Ý…Þ…ß…à…á…â…ã…ä…å"
				+ "³¢³£…æ…ç³¤…è…é…ê³¥…ë…ì…í…î…ï…ð…ñ³¦³§…ò³¨…ó³©…ô…õ…ö…÷…ø…ù"
				+ "³ª³«³¬…ú³­…û…ü³®³¯³°³±…ý…þ†A†B†C³²³³†D³´³µ³¶³·³¸†E³¹†F³º"
				+ "³»³¼†G†H³½†I†J†K³¾†L†M†N†O†P†Q†R³¿³À†S³Á³Â³Ã†T†U†V†W†X†Y"
				+ "³Ä³Å†Z†a³Æ†b†c†d³Ç†e†f†g†h†i†j†k³È†l†m†n†o³É†p†q†r†s†t†u"
				+ "†v†w†x†y†z††‚†ƒ†„†…†††‡†ˆ†‰†Š†‹†Œ††Ž†††‘†’†“†”†•†–†—"
				+ "³Ê³Ë†˜³Ì³Í†™†š†›³Î†œ³Ï³Ð††ž†Ÿ† ³Ñ³Ò†¡³Ó³Ô³Õ†¢†£†¤†¥†¦³Ö"
				+ "³×³Ø†§†¨³Ù†©†ª†«³Ú†¬†­†®†¯†°†±†²³Û³Ü†³³Ý³Þ³ß†´†µ†¶†·†¸†¹"
				+ "³à³á†º†»³â†¼†½†¾³ã†¿†À†Á†Â†Ã†Ä†Å³ä³å†Æ†Ç³æ³ç†È†É³è†Ê†Ë†Ì"
				+ "³é†Í†Î†Ï³ê†Ð†Ñ†Ò†Ó†Ô†Õ†Ö†×†Ø†Ù†Ú†Û†Ü†Ý†Þ†ß†à†á†â†ã†ä†å†æ"
				+ "³ë³ì†ç†è³í†é†ê†ë³î†ì³ï†í†î†ï†ð†ñ³ð³ñ†ò³ò†ó³ó†ô†õ†ö†÷³ô³õ"
				+ "³ö†ø†ù†ú³÷†û†ü†ý³ø†þ‡A‡B‡C‡D‡E‡F‡G‡H‡I‡J³ù‡K‡L‡M‡N‡O‡P‡Q"
				+ "‡R‡S‡T‡U‡V‡W‡X‡Y‡Z‡a‡b‡c‡d‡e‡f‡g‡h‡i‡j‡k‡l‡m‡n‡o‡p‡q‡r‡s"
				+ "³ú‡t‡u‡v³û‡w‡x‡y³ü‡z‡‡‚‡ƒ‡„‡…‡†³ý³þ‡‡´¡‡ˆ‡‰‡Š‡‹‡Œ‡‡Ž‡"
				+ "´¢´£‡‡‘´¤‡’‡“‡”´¥‡•‡–‡—‡˜‡™‡š‡›‡œ´¦‡´§‡ž´¨‡Ÿ‡ ‡¡‡¢‡£‡¤"
				+ "´©´ª‡¥‡¦´«‡§‡¨´¬´­‡©‡ª‡«‡¬‡­‡®‡¯´®´¯‡°´°‡±´±‡²‡³‡´‡µ‡¶‡·"
				+ "´²‡¸‡¹‡º‡»‡¼‡½‡¾‡¿‡À‡Á‡Â‡Ã‡Ä‡Å‡Æ‡Ç‡È‡É‡Ê´³‡Ë‡Ì‡Í‡Î‡Ï‡Ð‡Ñ"
				+ "´´‡Ò‡Ó‡Ô‡Õ‡Ö‡×‡Ø‡Ù‡Ú‡Û‡Ü‡Ý‡Þ‡ß‡à‡á‡â‡ã‡ä‡å‡æ‡ç‡è‡é‡ê‡ë‡ì"
				+ "´µ‡í‡î‡ï´¶‡ð‡ñ‡ò´·‡ó‡ô‡õ‡ö‡÷‡ø‡ù´¸´¹‡ú‡û‡ü‡ý‡þˆAˆBˆCˆDˆE"
				+ "´º´»ˆFˆGˆHˆIˆJˆK´¼ˆLˆMˆNˆOˆPˆQˆR´½´¾ˆSˆTˆU´¿ˆVˆWˆXˆYˆZˆa"
				+ "´À´Áˆbˆc´Âˆdˆeˆf´Ã´Ä´Åˆgˆhˆiˆjˆk´Æ´Çˆl´Èˆm´É´Êˆnˆoˆp´Ëˆq"
				+ "´Ìˆrˆsˆt´Íˆuˆvˆw´Îˆxˆyˆzˆˆ‚ˆƒˆ„ˆ…ˆ†ˆ‡ˆˆˆ‰ˆŠˆ‹ˆŒˆˆŽˆˆ"
				+ "´Ï´Ðˆ‘ˆ’´Ñˆ“ˆ”ˆ•´Òˆ–´Óˆ—ˆ˜ˆ™ˆšˆ›´Ô´Õˆœ´Öˆ´×ˆžˆŸˆ ˆ¡´Øˆ¢"
				+ "´Ù´Ú´Ûˆ£´Üˆ¤ˆ¥´Ý´Þ´ß´à´áˆ¦ˆ§ˆ¨´â´ã´äˆ©´å´æ´ç´è´éˆªˆ«ˆ¬´ê"
				+ "´ë´ìˆ­ˆ®´íˆ¯ˆ°ˆ±´îˆ²ˆ³ˆ´ˆµˆ¶ˆ·ˆ¸´ï´ðˆ¹´ñ´ò´óˆºˆ»ˆ¼ˆ½ˆ¾ˆ¿"
				+ "´ôˆÀˆÁˆÂˆÃˆÄˆÅˆÆˆÇˆÈˆÉˆÊˆËˆÌˆÍˆÎˆÏˆÐˆÑˆÒˆÓˆÔˆÕˆÖˆ×ˆØˆÙˆÚ"
				+ "ˆÛˆÜˆÝˆÞˆßˆàˆáˆâˆãˆäˆåˆæˆçˆèˆéˆêˆëˆìˆíˆîˆïˆðˆñˆòˆóˆôˆõˆö"
				+ "´õ´ö´÷ˆ÷´øˆøˆù´ù´úˆú´û´üˆûˆüˆýˆþ´ý´þ‰Aµ¡‰Bµ¢‰Cµ£‰D‰Eµ¤‰F"
				+ "µ¥µ¦‰G‰Hµ§‰I‰J‰Kµ¨‰L‰M‰N‰O‰P‰Q‰Rµ©µª‰Sµ«µ¬µ­‰T‰U‰V‰W‰X‰Y"
				+ "µ®‰Z‰a‰bµ¯‰c‰d‰eµ°‰f‰g‰h‰i‰j‰k‰l‰m‰n‰o‰pµ±µ²‰q‰r‰s‰t‰u‰v"
				+ "µ³‰w‰x‰yµ´‰z‰‰‚‰ƒ‰„‰…‰†‰‡‰ˆ‰‰‰Š‰‹‰Œ‰‰Ž‰‰‰‘‰’‰“‰”‰•‰–"
				+ "µµµ¶‰—‰˜µ·‰™‰šµ¸µ¹‰›µº‰œµ»‰‰ž‰Ÿµ¼µ½‰ µ¾‰¡µ¿‰¢µÀ‰£µÁ‰¤‰¥"
				+ "µÂ‰¦‰§‰¨µÃ‰©‰ª‰«µÄ‰¬‰­‰®‰¯‰°‰±‰²‰³‰´‰µ‰¶‰·‰¸‰¹‰º‰»‰¼‰½‰¾"
				+ "µÅ‰¿‰À‰Á‰Â‰Ã‰Ä‰Å‰Æ‰Ç‰È‰É‰Ê‰Ë‰Ì‰Í‰Î‰Ï‰Ð‰ÑµÆ‰Ò‰Ó‰Ô‰Õ‰Ö‰×‰Ø"
				+ "µÇ‰Ù‰Ú‰ÛµÈ‰Ü‰Ý‰ÞµÉ‰ß‰à‰á‰â‰ã‰ä‰åµÊµË‰æµÌ‰ç‰è‰é‰ê‰ë‰ì‰í‰î"
				+ "µÍ‰ï‰ð‰ñ‰ò‰ó‰ô‰õ‰ö‰÷‰ø‰ù‰ú‰û‰ü‰ý‰þŠAŠBŠCŠDŠEŠFŠGŠHŠIŠJŠK"
				+ "µÎµÏŠLŠMµÐŠNŠOŠPµÑŠQŠRŠSŠTŠUŠVŠWµÒµÓŠXµÔŠYµÕŠZŠaŠbŠcŠdŠe"
				+ "µÖŠfŠgŠhŠiŠjŠkŠlŠmŠnŠoŠpŠqŠrŠsŠtŠuŠvŠwŠxµ×ŠyŠzŠŠ‚ŠƒŠ„Š…"
				+ "µØŠ†Š‡ŠˆŠ‰ŠŠŠ‹ŠŒŠŠŽŠŠŠ‘Š’Š“Š”Š•Š–Š—Š˜Š™µÙŠšŠ›ŠœŠŠžŠŸ"
				+ "µÚŠ Š¡Š¢µÛŠ£Š¤Š¥µÜŠ¦Š§Š¨Š©ŠªŠ«Š¬Š­µÝŠ®µÞŠ¯µßŠ°Š±Š²Š³Š´Šµ"
				+ "µàŠ¶Š·Š¸µáŠ¹ŠºŠ»µâŠ¼Š½Š¾Š¿ŠÀŠÁŠÂµãŠÃŠÄŠÅŠÆµäŠÇŠÈŠÉŠÊŠËŠÌ"
				+ "µåµæŠÍŠÎµçŠÏŠÐµèµéŠÑµêŠÒŠÓŠÔŠÕŠÖµëµìŠ×µíŠØµîŠÙŠÚŠÛŠÜŠÝŠÞ"
				+ "µïŠßŠàŠáŠâŠãŠäŠåŠæŠçŠèŠéŠêŠëŠìŠíŠîŠïŠðŠñŠòŠóŠôŠõŠöŠ÷ŠøŠù"
				+ "µðµñŠúŠûµòŠüŠýµóµôŠþ‹A‹B‹C‹D‹E‹Fµõµö‹Gµ÷µøµùµú‹H‹I‹J‹K‹L"
				+ "µûµü‹M‹Nµý‹O‹P‹Qµþ‹R‹S‹T‹U‹V‹W‹X¶¡¶¢‹Y¶£¶¤¶¥‹Z‹a‹b‹c‹d¶¦"
				+ "¶§¶¨‹e‹f¶©‹g‹h‹i¶ª‹j‹k‹l‹m‹n‹o‹p¶«¶¬‹q¶­¶®¶¯‹r‹s‹t‹u‹v‹w"
				+ "‹x‹y‹z‹‹‚‹ƒ‹„‹…‹†‹‡‹ˆ‹‰‹Š‹‹‹Œ‹‹Ž‹‹‹‘‹’‹“‹”‹•‹–‹—‹˜‹™"
				+ "‹š‹›‹œ‹‹ž‹Ÿ‹ ‹¡‹¢‹£‹¤‹¥‹¦‹§‹¨‹©‹ª‹«‹¬‹­‹®‹¯‹°‹±‹²‹³‹´‹µ"
				+ "¶°¶±‹¶‹·¶²‹¸‹¹‹º¶³‹»¶´¶µ‹¼‹½‹¾‹¿¶¶¶·‹À¶¸¶¹¶º‹Á‹Â‹Ã‹Ä‹Å¶»"
				+ "¶¼¶½‹Æ‹Ç¶¾‹È‹É‹Ê¶¿‹Ë‹Ì‹Í‹Î‹Ï‹Ð‹Ñ¶À¶Á‹Ò¶Â¶Ã¶Ä‹Ó‹Ô‹Õ‹Ö‹×‹Ø"
				+ "¶Å‹Ù‹Ú‹Û‹Ü‹Ý‹Þ‹ß‹à‹á‹â‹ã‹ä‹å‹æ‹ç‹è‹é‹ê‹ë¶Æ‹ì‹í‹î‹ï‹ð‹ñ‹ò"
				+ "‹ó‹ô‹õ‹ö‹÷‹ø‹ù‹ú‹û‹ü‹ý‹þŒAŒBŒCŒDŒEŒFŒGŒHŒIŒJŒKŒLŒMŒNŒOŒP"
				+ "¶Ç¶ÈŒQŒR¶ÉŒSŒTŒU¶ÊŒVŒWŒXŒYŒZŒaŒbŒcŒdŒeŒfŒg¶ËŒhŒiŒjŒkŒlŒm"
				+ "¶ÌŒnŒoŒpŒqŒrŒsŒt¶ÍŒuŒvŒwŒxŒyŒzŒŒ‚ŒƒŒ„Œ…Œ†Œ‡ŒˆŒ‰ŒŠŒ‹ŒŒŒ"
				+ "¶ÎŒŽŒŒŒ‘Œ’Œ“Œ”Œ•Œ–Œ—Œ˜Œ™ŒšŒ›ŒœŒŒžŒŸŒ Œ¡Œ¢Œ£Œ¤Œ¥Œ¦Œ§Œ¨"
				+ "¶ÏŒ©ŒªŒ«¶ÐŒ¬Œ­Œ®Œ¯Œ°Œ±Œ²Œ³Œ´ŒµŒ¶Œ·Œ¸Œ¹ŒºŒ»Œ¼Œ½Œ¾Œ¿ŒÀŒÁŒÂ"
				+ "ŒÃŒÄŒÅŒÆŒÇŒÈŒÉŒÊŒËŒÌŒÍŒÎŒÏŒÐŒÑŒÒŒÓŒÔŒÕŒÖŒ×ŒØŒÙŒÚŒÛŒÜŒÝŒÞ"
				+ "¶Ñ¶ÒŒßŒà¶ÓŒáŒâŒã¶ÔŒäŒåŒæŒçŒèŒé¶Õ¶ÖŒêŒëŒìŒí¶×ŒîŒïŒðŒñŒòŒó"
				+ "ŒôŒõŒöŒ÷ŒøŒùŒúŒûŒüŒýŒþABCDEFGHIJKLMNOPQ"
				+ "¶ØRSTUVWXYZabcdefghijklmnopqr"
				+ "¶Ùstu¶Úvwx¶Ûyz‚ƒ„…¶Ü¶Ý†‡ˆ¶Þ‰Š‹ŒŽ"
				+ "‘’“”•–—˜™š›œžŸ ¡¢£¤¥¦§¨©ª"
				+ "¶ß¶à«¬¶á­®¶â¶ã¯°±²³´µ¶ä¶å¶¶æ·¸¹º»¼½¾"
				+ "¶ç¿ÀÁ¶èÂÃÄ¶éÅÆÇÈÉÊË¶ê¶ëÌÍÎÏÐÑÒÓÔÕ"
				+ "¶ìÖ×Ø¶íÙÚÛ¶îÜÝÞßàáâ¶ï¶ðã¶ñä¶òåæçèéê"
				+ "¶ó¶ôëì¶õíîï¶öðñòóôõö¶÷¶ø÷¶ù¶ú¶û¶üøùú¶ý¶þ"
				+ "·¡·¢ûü·£ýþŽA·¤ŽBŽCŽDŽEŽFŽGŽH·¥·¦ŽI·§·¨·©ŽJŽKŽLŽMŽNŽO"
				+ "·ª·«ŽPŽQ·¬ŽRŽSŽTŽUŽVŽWŽXŽYŽZŽaŽbŽcŽdŽe·­Žf·®ŽgŽhŽiŽjŽkŽl"
				+ "ŽmŽnŽoŽpŽqŽrŽsŽtŽuŽvŽwŽxŽyŽzŽŽ‚ŽƒŽ„Ž…Ž†Ž‡ŽˆŽ‰ŽŠŽ‹ŽŒŽŽŽ"
				+ "·¯·°ŽŽ·±Ž‘Ž’Ž“·²Ž”Ž•Ž–Ž—Ž˜Ž™Žš·³·´Ž›·µ·¶··ŽœŽŽžŽŸŽ ·¸"
				+ "·¹·ºŽ¡Ž¢·»Ž£Ž¤Ž¥·¼Ž¦Ž§Ž¨Ž©ŽªŽ«Ž¬·½·¾Ž­·¿Ž®·ÀŽ¯Ž°Ž±Ž²Ž³Ž´"
				+ "·Á·ÂŽµŽ¶·ÃŽ·Ž¸Ž¹·ÄŽºŽ»Ž¼Ž½Ž¾Ž¿ŽÀ·Å·ÆŽÁ·Ç·È·ÉŽÂŽÃŽÄŽÅŽÆŽÇ"
				+ "·ÊŽÈŽÉŽÊ·ËŽËŽÌŽÍŽÎŽÏŽÐŽÑŽÒŽÓŽÔŽÕŽÖ·ÌŽ×·ÍŽØŽÙŽÚŽÛŽÜŽÝŽÞŽß"
				+ "·Î·ÏŽàŽá·ÐŽâŽãŽä·ÑŽåŽæŽçŽèŽéŽêŽë·Ò·ÓŽì·ÔŽí·ÕŽîŽïŽðŽñŽòŽó"
				+ "·ÖŽôŽõŽö·×Ž÷ŽøŽùŽúŽûŽüŽýŽþABCDEFGH·ØIJKLMN"
				+ "OPQRSTUVWXYZabcdefgh·Ùijklmno"
				+ "·Úpqr·Ûstu·Üvwxyz‚·Ý·Þƒ·ß„·à…†‡ˆ‰Š"
				+ "·á‹Œ·âŽ·ã‘’“”•–—˜·ä™·åš·æ›œžŸ "
				+ "·ç·è¡¢·é£¤¥·ê¦§¨©ª«¬·ë·ì­·í®·î¯°±²³´"
				+ "·ïµ¶·¸¹º»¼½¾¿ÀÁÂÃÄÅÆÇ·ðÈÉÊËÌÍÎ"
				+ "·ñÏÐÑÒÓÔÕÖ×ØÙÚÛÜÝÞßàáâãäåæçèé"
				+ "·ò·óêë·ôìíî·õïðñòóôõ·öö÷·÷ø·øùúûüýþ"
				+ "·ù·úAB·ûCDE·üFGHIJKL·ý·þM¸¡N¸¢OPQRST"
				+ "¸£¸¤UV¸¥WXY¸¦Zabcdef¸§¸¨g¸©h¸ª¸«ij¸¬¸­k"
				+ "lmnopqrstuvwxyz‚ƒ„…†‡ˆ‰Š‹Œ"
				+ "¸®¸¯Ž¸°‘’¸±“”•–—˜™¸²¸³š¸´›¸µœžŸ ¡"
				+ "¸¶¸·¢£¸¸¤¸¹¸º¸»¸¼¸½¥¦§¨©¸¾¸¿ª¸À«¸Á¸Â¬­¸Ã®¸Ä"
				+ "¸Å¸Æ¯°¸Ç±²³¸È´µ¶·¸¹º¸É¸Ê»¸Ë¸Ì¸Í¸Î¼½¾¿À"
				+ "¸Ï¸ÐÁÂÃÄÅÆ¸ÑÇÈÉÊËÌÍÎÏÐÑÒ¸ÒÓÔÕÖ×Ø"
				+ "ÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóô"
				+ "¸Ó¸Ôõö¸Õ÷øù¸Öú¸×ûüýþ‘A¸Ø¸Ù‘B¸Ú‘C¸Û¸Ü‘D‘E‘F‘G¸Ý"
				+ "¸Þ¸ß‘H‘I¸à‘J‘K‘L¸á‘M‘N‘O‘P‘Q‘R‘S¸â¸ã‘T¸ä¸å¸æ‘U‘V‘W‘X‘Y‘Z"
				+ "¸ç¸è‘a‘b¸é‘c‘d‘e¸ê‘f‘g‘h‘i‘j‘k‘l‘m‘n‘o¸ë¸ì¸í‘p¸î‘q‘r‘s‘t"
				+ "¸ï‘u‘v‘w‘x‘y‘z‘‘‚‘ƒ‘„‘…‘†‘‡‘ˆ‘‰‘Š‘‹‘Œ‘‘Ž‘‘‘‘‘’‘“‘”‘•"
				+ "¸ð¸ñ‘–¸ò¸ó‘—‘˜‘™¸ô‘š¸õ‘›‘œ‘‘ž‘Ÿ¸ö¸÷‘ ¸ø‘¡¸ù‘¢‘£‘¤‘¥‘¦‘§"
				+ "¸ú‘¨‘©‘ª¸û‘«‘¬‘­‘®‘¯‘°‘±‘²‘³‘´‘µ‘¶‘·‘¸‘¹¸ü¸ý‘º‘»‘¼‘½‘¾‘¿"
				+ "‘À‘Á‘Â‘Ã‘Ä‘Å‘Æ‘Ç‘È‘É‘Ê‘Ë‘Ì‘Í‘Î‘Ï‘Ð‘Ñ‘Ò‘Ó‘Ô‘Õ‘Ö‘×‘Ø‘Ù‘Ú‘Û"
				+ "¸þ‘Ü‘Ý‘Þ¹¡‘ß‘à‘á¹¢‘â‘ã‘ä‘å‘æ‘ç‘è‘é¹£‘ê¹¤‘ë¹¥‘ì‘í‘î‘ï‘ð‘ñ"
				+ "¹¦‘ò‘ó‘ô¹§‘õ‘ö‘÷¹¨‘ø‘ù‘ú‘û‘ü‘ý‘þ’A¹©’B¹ª’C’D’E’F’G’H’I’J"
				+ "¹«¹¬¹­’K¹®’L’M¹¯¹°¹±¹²’N’O’P’Q’R¹³¹´’S¹µ’T¹¶’U’V’W¹·’X¹¸"
				+ "¹¹’Y’Z’a¹º’b’c’d¹»’e’f’g’h’i’j’k’l¹¼’m¹½’n’o’p’q’r’s’t’u"
				+ "¹¾’v’w’x’y’z’’‚’ƒ’„’…’†’‡’ˆ’‰’Š’‹’Œ’’Ž’’’‘’’’“’”’•’–"
				+ "¹¿’—’˜’™¹À’š’›’œ¹Á’’ž’Ÿ’ ’¡’¢’£’¤’¥’¦’§’¨’©’ª’«’¬’­’®’¯"
				+ "¹Â’°’±’²¹Ã’³’´’µ¹Ä’¶’·’¸’¹’º’»’¼¹Å’½’¾¹Æ’¿’À’Á’Â’Ã’Ä’Å’Æ"
				+ "¹Ç’Ç’È’É¹È’Ê’Ë’Ì¹É’Í’Î’Ï’Ð’Ñ’Ò’Ó¹Ê’Ô’Õ¹Ë’Ö’×’Ø’Ù’Ú’Û’Ü’Ý"
				+ "’Þ’ß’à’á’â’ã’ä’å’æ’ç’è’é’ê’ë’ì’í’î’ï’ð’ñ’ò’ó’ô’õ’ö’÷’ø’ù"
				+ "¹Ì¹Í’ú’û¹Î’ü’ý¹Ï¹Ð’þ¹Ñ“A“B“C“D“E¹Ò¹Ó“F¹Ô¹Õ¹Ö“G¹×“H¹Ø“I“J"
				+ "¹Ù¹Ú¹Û¹Ü¹Ý“K“L¹Þ¹ß¹à¹á¹â“M“N“O“P¹ã¹ä“Q¹å“R¹æ“S“T“U¹ç“V“W"
				+ "¹è¹é“X“Y¹ê“Z“a“b¹ë“c“d“e“f“g“h“i¹ì¹í“j¹î¹ï¹ð“k“l“m¹ñ“n“o"
				+ "¹ò¹ó“p“q¹ô“r“s“t“u“v“w“x“y“z““‚“ƒ¹õ“„“…“†“‡“ˆ“‰“Š“‹“Œ“"
				+ "“Ž“““‘“’“““”“•“–“—“˜“™“š“›“œ““ž“Ÿ“ “¡“¢“£“¤“¥“¦“§“¨“©"
				+ "¹ö¹÷“ª“«¹ø“¬“­¹ù¹ú“®¹û“¯“°“±“²“³¹ü¹ý“´¹þ“µº¡º¢“¶“·“¸“¹“º"
				+ "º£º¤“»“¼º¥“½“¾º¦º§“¿“À“Á“Â“Ã“Ä“Åº¨º©“Æºªº«º¬“Ç“È“É“Ê“Ë“Ì"
				+ "º­º®“Í“Îº¯“Ï“Ð“Ñº°“Ò“Ó“Ô“Õ“Ö“×“Ø“Ùº±“Úº²º³º´“Û“Ü“Ýºµ“Þ“ß"
				+ "º¶“à“á“âº·“ã“ä“å“æ“ç“è“é“ê“ë“ì“í“î“ï“ð“ñ“ò“ó“ô“õ“ö“÷“ø“ù"
				+ "º¸º¹ºº“úº»“û“ü“ýº¼“þ”A”B”C”D”E”Fº½º¾”Gº¿”HºÀ”I”J”K”L”M”N"
				+ "ºÁ”O”P”QºÂ”R”S”T”U”V”W”X”Y”Z”a”b”c”d”e”fºÃ”g”h”i”j”k”l”m"
				+ "ºÄ”n”o”p”q”r”s”t”u”v”w”x”y”z””‚”ƒ”„”…”†ºÅ”‡”ˆ”‰”Š”‹”Œ”"
				+ "ºÆºÇ”Ž”ºÈ””‘”’ºÉ”“”””•”–”—”˜”™ºÊºË”š”›”œ””ž”Ÿ” ”¡”¢”£"
				+ "ºÌ”¤”¥”¦ºÍ”§”¨”©”ª”«”¬”­”®”¯”°”±”²”³”´”µ”¶”·”¸”¹”º”»”¼”½"
				+ "ºÎºÏ”¾”¿ºÐ”À”ÁºÑºÒºÓºÔ”Â”Ã”Ä”Å”ÆºÕºÖ”Çº×”ÈºØ”É”Ê”ËºÙºÚ”Ì"
				+ "ºÛ”Í”Î”Ï”Ð”Ñ”Ò”ÓºÜ”Ô”Õ”Ö”×”Ø”Ù”Ú”Û”Ü”Ý”ÞºÝ”ß”à”á”â”ã”ä”å"
				+ "ºÞ”æ”ç”è”é”ê”ë”ì”í”î”ï”ð”ñ”ò”ó”ô”õ”ö”÷”ø”ù”ú”û”ü”ý”þ•A•B"
				+ "ºßºà•C•Dºá•E•F•Gºâ•H•I•J•K•L•M•N•O•P•Q•R•Sºã•T•U•V•W•X•Y"
				+ "ºä•Z•a•bºå•c•d•eºæ•f•g•h•i•j•k•lºç•m•nºè•oºé•p•q•r•s•t•u"
				+ "ºêºë•v•wºì•x•y•zºí••‚•ƒ•„•…•†•‡ºîºï•ˆºð•‰•Š•‹•Œ••Ž••"
				+ "•‘•’•“•”•••–•—•˜•™•š•›•œ••ž•Ÿ• •¡•¢•£•¤•¥•¦•§•¨•©•ª•«•¬"
				+ "ºñºò•­•®ºó•¯•°•±ºô•²ºõ•³•´•µ•¶•·ºöº÷•¸ºø•¹ºùºúºû•º•»•¼•½"
				+ "ºüºý•¾•¿ºþ•À•Á•Â»¡•Ã»¢•Ä•Å•Æ•Ç•È»£»¤•É»¥»¦»§•Ê•Ë•Ì•Í•Î»¨"
				+ "»©»ª•Ï•Ð»«•Ñ•Ò•Ó»¬•Ô•Õ•Ö•×•Ø•Ù•Ú»­»®•Û»¯»°»±•Ü•Ý•Þ•ß•à•á"
				+ "»²»³•â•ã•ä•å•æ•ç•è•é•ê•ë•ì•í•î•ï»´•ð•ñ•ò•ó•ô•õ•ö•÷•ø•ù•ú"
				+ "•û•ü•ý•þ–A–B–C–D–E–F–G–H–I–J–K–L–M–N–O–P–Q–R–S–T–U–V–W–X"
				+ "»µ»¶–Y–Z»·–a–b»¸»¹–c–d–e–f–g–h–i»º–j–k»»»¼»½–l–m–n–o–p–q"
				+ "»¾–r–s–t–u–v–w–x–y–z––‚–ƒ–„–…–†–‡–ˆ–‰–Š–‹»¿–Œ––Ž–––‘"
				+ "»À»Á–’–“–”–•–––—–˜–™–š–›–œ––ž–Ÿ»Â»Ã– »Ä»Å»Æ–¡–¢–£–¤–¥–¦"
				+ "–§–¨–©–ª–«–¬–­–®–¯–°–±–²–³–´–µ–¶–·–¸–¹–º–»–¼–½–¾–¿–À–Á–Â"
				+ "»Ç»È–Ã–Ä»É–Å–Æ–Ç»Ê–È–É–Ê–Ë–Ì–Í–Î»Ë»Ì–Ï–Ð–Ñ»Í–Ò–Ó–Ô–Õ–Ö–×"
				+ "–Ø–Ù–Ú–Û–Ü–Ý–Þ–ß–à–á–â–ã–ä–å–æ–ç–è–é–ê–ë–ì–í–î–ï–ð–ñ–ò–ó"
				+ "–ô–õ–ö–÷–ø–ù–ú–û–ü–ý–þ—A—B—C—D—E—F—G—H—I—J—K—L—M—N—O—P—Q"
				+ "»Î—R—S—T—U—V—W—X—Y—Z—a—b—c—d—e—f—g—h—i—j—k—l—m—n—o—p—q—r"
				+ "»Ï—s—t—u—v—w—x—y—z——‚—ƒ—„—…—†—‡—ˆ—‰—Š—‹—Œ»Ð——Ž———‘—’"
				+ "»Ñ»Ò—“—”»Ó—•—–——»Ô—˜—™—š—›—œ——ž»Õ—Ÿ— »Ö—¡»×—¢—£—¤—¥—¦—§"
				+ "—¨—©—ª—«—¬—­—®—¯—°—±—²—³—´—µ—¶—·—¸—¹—º—»—¼—½—¾—¿—À—Á—Â—Ã"
				+ "—Ä—Å—Æ—Ç—È—É—Ê—Ë—Ì—Í—Î—Ï—Ð—Ñ—Ò—Ó—Ô—Õ—Ö—×—Ø—Ù—Ú—Û—Ü—Ý—Þ—ß"
				+ "—à—á—â—ã—ä—å—æ—ç—è—é—ê—ë—ì—í—î—ï—ð—ñ—ò—ó—ô—õ—ö—÷—ø—ù—ú—û"
				+ "»Ø—ü—ý—þ˜A˜B˜C˜D˜E˜F˜G˜H˜I˜J˜K˜L˜M˜N˜O˜P˜Q»Ù˜R˜S˜T˜U˜V˜W"
				+ "»Ú˜X˜Y˜Z»Û˜a˜b˜c»Ü˜d˜e˜f˜g˜h˜i˜j»Ý»Þ˜k˜l˜m˜n˜o˜p˜q˜r˜s˜t"
				+ "˜u˜v˜w˜x˜y˜z˜˜‚˜ƒ˜„˜…˜†˜‡˜ˆ˜‰˜Š˜‹˜Œ˜˜Ž˜˜˜‘˜’˜“˜”˜•˜–"
				+ "»ß»à˜—˜˜»á˜™˜š˜›»â˜œ˜˜ž˜Ÿ˜ ˜¡˜¢»ã»ä˜£»å˜¤»æ˜¥˜¦˜§˜¨˜©˜ª"
				+ "»ç»è˜«»é»ê˜¬˜­»ë»ì»í»î˜®˜¯˜°˜±˜²»ï»ð˜³»ñ»ò»ó˜´˜µ˜¶»ô˜·˜¸"
				+ "»õ»ö˜¹˜º»÷˜»˜¼˜½»ø˜¾˜¿˜À˜Á˜Â˜Ã˜Ä»ù»ú˜Å»û»ü»ý˜Æ˜Ç˜È˜É˜Ê˜Ë"
				+ "»þ¼¡˜Ì˜Í¼¢˜Î˜Ï˜Ð¼£˜Ñ˜Ò˜Ó˜Ô˜Õ˜Ö˜×¼¤¼¥˜Ø¼¦˜Ù¼§˜Ú˜Û˜Ü˜Ý˜Þ˜ß"
				+ "¼¨˜à˜á˜â¼©˜ã˜ä˜å¼ª˜æ˜ç˜è˜é˜ê˜ë˜ì¼«˜í˜î˜ï˜ð¼¬˜ñ˜ò˜ó˜ô˜õ˜ö"
				+ "¼­¼®¼¯¼°¼±˜÷˜ø¼²¼³˜ù¼´¼µ˜ú˜û˜ü˜ý¼¶¼·˜þ¼¸¼¹¼º™A™B™C™D¼»™E"
				+ "¼¼¼½™F™G¼¾™H™I™J¼¿™K™L™M™N™O™P™Q¼À¼Á™R¼Â¼Ã¼Ä™S™T™U™V™W™X"
				+ "¼Å¼Æ™Y™Z¼Ç™a™b™c¼È™d™e™f™g™h™i™j¼É¼Ê™k¼Ë¼Ì¼Í™l™m™n™o™p™q"
				+ "¼Î™r™s™t¼Ï™u™v™w¼Ð™x™y™z™™‚™ƒ™„™…™†™‡™ˆ™‰¼Ñ™Š™‹™Œ™™Ž™"
				+ "¼Ò¼Ó¼Ô™¼Õ™‘™’™“¼Ö™”¼×™•™–™—™˜™™¼Ø¼Ù™š¼Ú™›¼Û™œ™™ž¼Ü™Ÿ™ "
				+ "¼Ý¼Þ™¡™¢¼ß™£™¤™¥¼à™¦™§™¨™©™ª™«™¬™­™®™¯™°™±¼á™²™³™´™µ™¶™·"
				+ "¼â™¸™¹™º¼ã™»™¼™½¼ä™¾™¿™À™Á™Â™Ã™Ä¼å™Å™Æ¼æ¼ç™Ç™È™É™Ê™Ë™Ì™Í"
				+ "¼è™Î™Ï™Ð¼é™Ñ™Ò™Ó¼ê™Ô™Õ™Ö™×™Ø™Ù™Ú¼ë¼ì™Û¼í™Ü™Ý™Þ™ß™à™á™â™ã"
				+ "¼î¼ï™ä™å¼ð™æ™ç™è¼ñ™é™ê™ë™ì™í™î™ï¼ò¼ó™ð¼ô™ñ¼õ™ò™ó™ô™õ™ö™÷"
				+ "¼ö¼÷™ø™ù¼ø™ú™û¼ù¼ú™ü™ý™þšAšBšCšD¼û¼üšE¼ýšF¼þšG½¡šH½¢½£šI"
				+ "½¤šJšKšLšMšNšOšPšQšRšSšTšUšVšWšXšYšZšašb½¥šcšdšešfšgšhši"
				+ "½¦½§šjšk½¨šlšmšn½©šošpšqšršsštšu½ªšvšwšxšy½«šzšš‚šƒš„š…"
				+ "½¬½­š†š‡½®šˆš‰šŠ½¯š‹šŒššŽššš‘½°½±š’½²š“½³š”š•š–š—š˜š™"
				+ "½´½µššš›šœššžšŸ½¶š š¡š¢š£š¤š¥š¦½·š§š¨½¸š©½¹šªš«š¬š­š®š¯"
				+ "½º½»š°š±½¼š²š³š´½½½¾šµš¶š·š¸š¹šº½¿½Àš»½Áš¼½Âš½š¾š¿šÀšÁšÂ"
				+ "šÃšÄšÅšÆšÇšÈšÉšÊšËšÌšÍšÎšÏšÐšÑšÒšÓšÔšÕšÖš×šØšÙšÚšÛšÜšÝšÞ"
				+ "½Ã½Äšßšà½Åšášâ½Æ½Çšãšäšåšæšçšè½È½É½Êšé½Ëšê½Ìšëšìšíšî½Íšï"
				+ "½Î½Ïšð½Ð½Ñšñšòšó½Òšôšõšöš÷šøšùšú½Ó½Ôšûšü½Õ½Öšýšþ›A›B›C½×"
				+ "½Ø½Ù›D›E½Ú›F›G›H½Û›I›J›K›L›M›N›O½Ü½Ý›P›Q½Þ½ß›R›S›T›U›V›W"
				+ "›X›Y›Z›a›b›c›d›e›f›g›h›i›j›k›l›m›n›o›p›q›r½à›s›t›u›v›w›x"
				+ "›y›z››‚›ƒ›„›…›†›‡›ˆ›‰›Š›‹›Œ››Ž›››‘›’›“›”›•›–›—›˜›™›š"
				+ "½á½â›››œ½ã››ž›Ÿ½ä› ½å›¡›¢›£›¤›¥½æ½ç›¦›§½è½é›¨›©›ª›«›¬›­"
				+ "½ê›®›¯›°½ë›±›²›³½ì›´›µ›¶›·›¸›¹›º›»›¼›½›¾›¿›À›Á›Â›Ã›Ä›Å›Æ"
				+ "›Ç›È›É›Ê›Ë›Ì›Í›Î›Ï›Ð›Ñ›Ò›Ó›Ô›Õ›Ö›×›Ø›Ù›Ú›Û›Ü›Ý›Þ›ß›à›á›â"
				+ "›ã›ä›å›æ½í›ç›è›é›ê›ë›ì›í›î›ï›ð›ñ›ò›ó›ô›õ›ö›÷›ø›ù›ú›û›ü›ý"
				+ "½î½ï›þœA½ðœBœC½ñ½òœD½óœEœFœGœHœI½ô½õœJœKœL½öœMœNœOœPœQœR"
				+ "½÷½øœSœT½ùœUœVœWœXœYœZœaœbœcœdœeœfœgœhœi½úœjœkœlœmœnœoœp"
				+ "½ûœqœrœsœtœuœvœwœxœyœzœœ‚œƒœ„œ…œ†œ‡œˆœ‰½üœŠœ‹œŒœœŽœœ"
				+ "½ýœ‘œ’œ“½þœ”œ•œ–¾¡œ—œ˜œ™œšœ›œœœ¾¢¾£œžœŸœ œ¡œ¢œ£œ¤œ¥œ¦œ§"
				+ "¾¤œ¨œ©œªœ«œ¬œ­œ®œ¯œ°œ±œ²œ³œ´œµœ¶œ·œ¸œ¹œºœ»œ¼œ½œ¾œ¿œÀœÁœÂ"
				+ "¾¥¾¦œÃœÄ¾§œÅœÆœÇ¾¨œÈœÉœÊœËœÌœÍœÎ¾©¾ªœÏœÐœÑ¾«œÒœÓœÔœÕœÖœ×"
				+ "¾¬œØœÙœÚœÛœÜœÝœÞœßœàœáœâœãœäœåœæœçœèœéœê¾­œëœìœíœîœïœðœñ"
				+ "¾®œòœóœôœõœöœ÷œøœùœúœûœüœýœþABCDEFGHIJKLMN"
				+ "¾¯OPQ¾°RSTUVWXYZabcdefghijklmn"
				+ "opqrstuvwxyz‚ƒ„…†‡ˆ‰¾±Š‹ŒŽ"
				+ "¾²¾³‘¾´’“”¾µ•¾¶–—˜™¾·¾¸¾¹š›œžŸ ¡¢£"
				+ "¾º¤¥¦¾»§¨©¾¼ª«¬­®¯°¾½±²³´µ¶·¸¹º»"
				+ "¾¾¾¿¼½¾À¾¿À¾ÁÁÂÃÄÅÆÇ¾Â¾ÃÈ¾ÄÉ¾ÅÊËÌÍÎÏ"
				+ "¾Æ¾ÇÐÑ¾È¾É¾ÊÒ¾Ë¾Ì¾ÍÓÔÕÖ¾Î¾Ï¾Ð×¾Ñ¾Ò¾ÓØÙÚ¾Ô¾ÕÛ"
				+ "¾Ö¾×ÜÝ¾ØÞßà¾Ùáâãäåæç¾Ú¾Ûè¾Ü¾Ý¾Þéêëìíî"
				+ "¾ß¾àïð¾áñòó¾âôõ¾ãö÷øù¾ä¾åú¾æû¾çüýþ¾èžA¾é"
				+ "¾êžBžCžD¾ëžEžFžG¾ìžHžIžJžKžLžMžNžO¾ížPžQžRžSžTžUžVžWžXžY"
				+ "¾î¾ïžZža¾ð¾ñžb¾ò¾ó¾ô¾õžcždžežfžg¾ö¾÷¾ø¾ù¾ú¾û¾üžh¾ýži¾þžj"
				+ "¿¡¿¢žkžl¿£žmžnžo¿¤žpžqžržsžtžužv¿¥¿¦žw¿§žx¿¨žyžzžž‚žƒž„"
				+ "¿©¿ª¿«ž…¿¬ž†ž‡žˆ¿­ž‰¿®¿¯žŠž‹žŒž¿°¿±¿²¿³¿´¿µžŽžž¿¶¿·¿¸"
				+ "¿¹ž‘ž’ž“¿ºž”ž•ž–¿»ž—ž˜ž™žšž›žœž¿¼¿½žž¿¾¿¿žŸž ž¡ž¢ž£ž¤ž¥"
				+ "¿À¿Áž¦ž§¿Âž¨ž©žª¿Ã¿Ä¿Åž«¿Æž¬ž­¿Ç¿È¿Éž®¿Êž¯¿Ëž°¿Ìž±ž²ž³ž´"
				+ "¿Í¿Îžµž¶¿Ïž·ž¸ž¹¿Ðžºž»ž¼ž½ž¾ž¿žÀ¿Ñ¿ÒžÁ¿Ó¿Ô¿ÕžÂžÃžÄžÅžÆžÇ"
				+ "¿Ö¿×žÈžÉ¿ØžÊžËžÌžÍžÎžÏžÐžÑžÒžÓžÔ¿ÙžÕžÖ¿Úž×¿ÛžØžÙžÚžÛžÜžÝ"
				+ "¿Ü¿ÝžÞžß¿Þžàžážâ¿ßžãžäžåžæžçžèžé¿à¿ážê¿âžë¿ãžìžížîžïžðžñ"
				+ "¿ä¿åžòžó¿æžôžõžö¿çž÷žøžùžúžûžüžý¿è¿éžþ¿êŸA¿ëŸBŸCŸDŸEŸFŸG"
				+ "¿ì¿íŸHŸI¿îŸJŸKŸL¿ï¿ð¿ñŸMŸNŸOŸPŸQ¿ò¿óŸR¿ôŸS¿õŸTŸUŸVŸWŸXŸY"
				+ "¿ö¿÷ŸZŸa¿øŸbŸcŸd¿ùŸeŸfŸgŸhŸiŸjŸk¿ú¿ûŸlŸm¿ü¿ýŸnŸoŸpŸqŸrŸs"
				+ "¿þÀ¡ŸtŸuÀ¢ŸvŸwŸxÀ£ŸyŸzŸŸ‚ŸƒŸ„Ÿ…À¤À¥Ÿ†Ÿ‡ŸˆÀ¦Ÿ‰ŸŠŸ‹ŸŒŸŸŽ"
				+ "À§À¨ŸŸÀ©Ÿ‘Ÿ’Ÿ“ÀªŸ”Ÿ•Ÿ–Ÿ—Ÿ˜Ÿ™ŸšÀ«À¬Ÿ›À­ŸœÀ®ŸŸžŸŸŸ Ÿ¡Ÿ¢"
				+ "À¯À°Ÿ£Ÿ¤À±Ÿ¥Ÿ¦Ÿ§À²Ÿ¨Ÿ©ŸªŸ«Ÿ¬Ÿ­Ÿ®À³À´Ÿ¯ÀµŸ°À¶Ÿ±À·Ÿ²Ÿ³Ÿ´Ÿµ"
				+ "À¸À¹Ÿ¶Ÿ·ÀºŸ¸Ÿ¹ŸºÀ»Ÿ»Ÿ¼Ÿ½Ÿ¾Ÿ¿À¼ŸÀÀ½À¾ŸÁÀ¿ŸÂÀÀÀÁÀÂÀÃÀÄÀÅÀÆ"
				+ "ÀÇŸÃŸÄŸÅÀÈŸÆŸÇŸÈÀÉŸÉŸÊŸËŸÌŸÍŸÎŸÏÀÊŸÐŸÑÀËŸÒŸÓŸÔŸÕŸÖŸ×ŸØŸÙ"
				+ "ÀÌÀÍŸÚŸÛÀÎŸÜŸÝŸÞÀÏÀÐÀÑŸßŸàŸáŸâÀÒÀÓÀÔŸãÀÕÀÖÀ×ÀØŸäŸåŸæÀÙŸç"
				+ "ÀÚÀÛŸèŸéÀÜŸêÀÝÀÞÀßŸëÀàŸìŸíŸîŸïŸðÀáÀâŸñÀãÀäÀåÀæŸòŸóŸôŸõŸö"
				+ "ÀçÀèŸ÷ŸøÀéŸùŸúŸûÀêŸüŸýŸþ A B C DÀëÀì EÀíÀîÀï F G H I J K"
				+ "ÀðÀñ L MÀò NÀó OÀô P Q R S T U VÀõ W X Y ZÀö a b c d e f"
				+ "À÷ g h iÀø j k lÀù m n o p q r s t u v w x y z  ‚ ƒ „ …"
				+ "ÀúÀû † ‡Àü ˆ ‰ ŠÀý ‹Àþ Œ  Ž  Á¡Á¢ ‘Á£ ’Á¤Á¥ “ ” • – —"
				+ "Á¦Á§ ˜ ™Á¨ š › œÁ©  ž Ÿ   ¡ ¢ £ÁªÁ« ¤Á¬ ¥Á­ ¦ § ¨ © ª «"
				+ "Á® ¬ ­ ®Á¯ ¯ ° ±Á° ² ³ ´ µ ¶ · ¸Á±Á² ¹ ºÁ³Á´ » ¼ ½ ¾ ¿ À"
				+ "Áµ Á Â Ã Ä Å Æ Ç È É Ê Ë Ì Í Î Ï Ð Ñ Ò Ó Ô Õ Ö × Ø Ù Ú Û"
				+ "Á¶Á· Ü ÝÁ¸ Þ ß àÁ¹ áÁº â ã ä å æÁ»Á¼ çÁ½ èÁ¾Á¿ÁÀ é ê ëÁÁ"
				+ "ÁÂÁÃ ì í î ï ð ñÁÄ ò ó ô õ ö ÷ ø ùÁÅ úÁÆ ûÁÇ ü ý þ¡A¡B¡C"
				+ "ÁÈ¡D¡E¡F¡G¡H¡I¡J¡K¡L¡M¡N¡O¡P¡Q¡R¡S¡T¡U¡VÁÉÁÊ¡W¡X¡Y¡Z¡a¡b"
				+ "ÁË¡c¡d¡eÁÌ¡f¡g¡hÁÍ¡i¡j¡k¡l¡m¡n¡oÁÎÁÏ¡pÁÐ¡qÁÑ¡r¡s¡t¡u¡v¡w"
				+ "ÁÒÁÓ¡x¡yÁÔ¡z¡¡‚¡ƒ¡„¡…¡†¡‡¡ˆ¡‰¡Š¡‹¡Œ¡¡Ž¡ÁÕ¡¡‘¡’¡“¡”¡•"
				+ "ÁÖÁ×¡–¡—ÁØ¡˜¡™¡šÁÙÁÚÁÛ¡›¡œ¡¡ž¡ŸÁÜÁÝ¡ ÁÞ¢AÁß¢B¢C¢D¢E¢F¢G"
				+ "Áà¢H¢I¢J¢K¢L¢M¢N¢O¢P¢Q¢R¢S¢T¢U¢V¢W¢X¢Y¢ZÁá¢a¢b¢c¢d¢e¢f¢g"
				+ "Áâ¢h¢i¢j¢k¢l¢m¢n¢o¢p¢q¢r¢s¢t¢u¢v¢w¢x¢y¢z¢¢‚¢ƒ¢„¢…¢†¢‡¢ˆ"
				+ "ÁãÁä¢‰¢ŠÁå¢‹¢Œ¢Áæ¢Ž¢¢¢‘¢’¢“¢”ÁçÁè¢•Áé¢–¢—¢˜¢™¢š¢›¢œ¢"
				+ "Áê¢ž¢Ÿ¢ Áë£A£B£CÁì£D£E£F£G£H£I£JÁí£K£L£M£N£O£P£Q£R£S£T£U"
				+ "ÁîÁï£V£WÁð£X£Y£ZÁñ£a£b£c£d£e£f£gÁòÁó£hÁô£iÁõ£j£k£l£m£n£o"
				+ "£p£q£r£s£t£u£v£w£x£y£z££‚£ƒ£„£…£†£‡£ˆ£‰£Š£‹£Œ££Ž£££‘"
				+ "ÁöÁ÷£’£“Áø£”£•ÁùÁú£–Áû£—£˜£™£š£›ÁüÁý£œÁþ£Â¡Â¢£ž£ŸÂ£Â¤£ "
				+ "Â¥Â¦¤A¤BÂ§¤CÂ¨¤DÂ©¤E¤FÂª¤G¤H¤I¤JÂ«Â¬¤KÂ­Â®Â¯¤L¤M¤N¤O¤P¤Q"
				+ "Â°Â±¤R¤SÂ²¤T¤U¤VÂ³¤W¤X¤Y¤Z¤a¤b¤cÂ´Âµ¤dÂ¶Â·Â¸¤e¤f¤g¤h¤i¤j"
				+ "Â¹¤k¤l¤mÂº¤n¤o¤p¤q¤r¤s¤t¤u¤v¤w¤x¤y¤z¤¤‚¤ƒÂ»¤„¤…¤†¤‡¤ˆ¤‰"
				+ "¤Š¤‹¤Œ¤¤Ž¤¤¤‘¤’¤“¤”¤•¤–¤—¤˜¤™¤š¤›¤œ¤¤ž¤Ÿ¤ ¥A¥B¥C¥D¥E"
				+ "Â¼Â½¥F¥GÂ¾¥H¥I¥JÂ¿¥K¥L¥M¥N¥O¥P¥QÂÀÂÁ¥RÂÂÂÃÂÄ¥S¥T¥U¥V¥W¥X"
				+ "ÂÅ¥Y¥Z¥a¥b¥c¥d¥e¥f¥g¥h¥i¥j¥k¥l¥m¥n¥o¥p¥q¥rÂÆ¥s¥t¥u¥v¥w¥x"
				+ "ÂÇ¥y¥z¥¥‚¥ƒ¥„¥…¥†¥‡¥ˆ¥‰¥Š¥‹¥Œ¥¥Ž¥¥¥‘ÂÈ¥’¥“¥”¥•¥–¥—¥˜"
				+ "¥™¥š¥›¥œ¥¥ž¥Ÿ¥ ¦A¦B¦C¦D¦E¦F¦G¦H¦I¦J¦K¦L¦M¦N¦O¦P¦Q¦R¦S¦T"
				+ "ÂÉÂÊ¦U¦VÂË¦W¦X¦YÂÌ¦Z¦a¦b¦c¦d¦e¦fÂÍÂÎ¦gÂÏ¦hÂÐ¦iÂÑ¦j¦k¦l¦m"
				+ "ÂÒÂÓ¦n¦o¦p¦q¦r¦sÂÔ¦t¦u¦v¦w¦x¦y¦z¦¦‚¦ƒ¦„ÂÕ¦…¦†¦‡¦ˆ¦‰¦Š¦‹"
				+ "ÂÖ¦Œ¦¦Ž¦¦¦‘¦’¦“¦”¦•¦–¦—¦˜¦™¦š¦›¦œ¦¦žÂ×¦Ÿ¦ §A§B§C§D§E"
				+ "ÂØ§F§G§HÂÙ§I§J§KÂÚ§L§M§N§O§P§Q§RÂÛÂÜ§S§T§U§V§W§X§Y§Z§a§b"
				+ "§c§d§e§f§g§h§i§j§k§l§m§n§o§p§q§r§s§t§u§v§wÂÝ§x§y§z§§‚§ƒ"
				+ "ÂÞÂß§„§…Âà§†§‡§ˆÂá§‰§Š§‹§Œ§§Ž§ÂâÂã§§‘§’Âä§“§”§•§–§—§˜"
				+ "Âå§™§š§›§œ§§ž§Ÿ§ ¨A¨B¨C¨D¨E¨F¨G¨H¨I¨J¨KÂæÂç¨L¨M¨N¨O¨P¨Q"
				+ "¨R¨S¨T¨U¨V¨W¨X¨Y¨Z¨a¨b¨c¨d¨e¨f¨g¨h¨i¨j¨k¨l¨m¨n¨o¨p¨q¨r¨s"
				+ "Âè¨t¨u¨v¨w¨x¨y¨z¨¨‚¨ƒ¨„¨…¨†¨‡¨ˆ¨‰¨Š¨‹¨Œ¨¨Ž¨¨¨‘¨’¨“¨”"
				+ "Âé¨•¨–¨—¨˜¨™¨š¨›¨œ¨¨ž¨Ÿ¨ ©A©B©C©D©E©F©G©H©I©J©K©L©M©N©O"
				+ "Âê©P©Q©R©S©T©U©V©W©X©Y©Z©a©b©c©dÂë©e©fÂì©gÂí©h©i©j©k©l©m"
				+ "©n©o©p©q©r©s©t©u©v©w©x©y©z©©‚©ƒ©„©…©†©‡©ˆ©‰©Š©‹©Œ©©Ž©"
				+ "ÂîÂï©©‘Âð©’©“©”Âñ©•©–©—©˜©™©š©›ÂòÂó©œ©©žÂôÂõ©Ÿ© ªAªBÂö"
				+ "Â÷ÂøªCªDÂùªEÂúªFÂûªGªHªIªJªKªLªMÂüÂýªNÂþÃ¡Ã¢Ã£ªOªPªQªRªS"
				+ "Ã¤Ã¥ªTªUÃ¦ªVªWªXÃ§ªYªZªaªbªcªdªeÃ¨Ã©ªfÃªÃ«Ã¬ªgªhªiªjªkªl"
				+ "Ã­ªmªnªoÃ®ªpÃ¯ªqÃ°ªrªsªtªuªvªwªxÃ±ªyªzªª‚Ã²ªƒª„ª…ª†ª‡ªˆ"
				+ "ª‰ªŠª‹ªŒªªŽªªª‘ª’ª“ª”ª•ª–ª—ª˜ª™ªšª›ªœªªžªŸª «A«B«C«D"
				+ "Ã³Ã´«E«FÃµ«G«H«IÃ¶«J«K«L«M«N«O«PÃ·Ã¸«QÃ¹ÃºÃ»«R«S«T«U«V«W"
				+ "Ã¼Ã½«X«YÃ¾«Z«a«bÃ¿«c«d«e«f«g«h«iÃÀÃÁ«jÃÂ«kÃÃ«l«m«n«o«p«q"
				+ "ÃÄ«r«s«tÃÅ«u«v«w«x«y«z««‚«ƒ«„«…«†«‡«ˆ«‰ÃÆ«Š«‹«Œ««Ž««"
				+ "ÃÇ«‘«’«“ÃÈ«”«•«–«—«˜«™«š«›«œ««ž«Ÿ« ¬A¬B¬CÃÉ¬D¬E¬F¬G¬H¬I"
				+ "ÃÊÃË¬J¬KÃÌ¬L¬M¬NÃÍ¬O¬P¬Q¬R¬S¬T¬UÃÎÃÏ¬VÃÐ¬WÃÑ¬X¬Y¬Z¬a¬b¬c"
				+ "ÃÒ¬d¬e¬fÃÓ¬g¬h¬iÃÔ¬j¬k¬l¬m¬n¬o¬p¬q¬r¬s¬t¬uÃÕ¬v¬w¬x¬y¬z¬"
				+ "¬‚¬ƒ¬„¬…¬†¬‡¬ˆ¬‰¬Š¬‹¬Œ¬¬Ž¬¬¬‘¬’¬“¬”¬•¬–¬—¬˜¬™¬š¬›¬œ¬"
				+ "ÃÖ¬ž¬Ÿ¬ Ã×­A­B­CÃØ­D­E­F­G­H­I­JÃÙÃÚ­KÃÛ­LÃÜ­M­N­O­P­Q­R"
				+ "ÃÝ­S­T­U­V­W­X­Y­Z­a­b­c­d­e­f­gÃÞ­h­i­j­k­l­m­n­o­p­q­r"
				+ "ÃßÃà­s­tÃá­u­v­wÃâ­x­y­z­­‚­ƒ­„ÃãÃä­…Ãå­†Ãæ­‡­ˆ­‰­Š­‹­Œ"
				+ "Ãç­­Ž­­­‘­’­“­”­•­–­—­˜­™­š­›­œ­­ž­ŸÃè­ ®A®B®C®D®E®F"
				+ "Ãé®G®H®IÃê®J®K®L®M®N®O®P®Q®R®S®T®U®V®W®X®Y®Z®a®b®c®d®e®f"
				+ "Ãë®g®h®iÃì®j®k®lÃí®m®n®o®p®q®r®sÃîÃï®tÃð®uÃñ®v®w®x®y®z®"
				+ "Ãò®‚®ƒ®„Ãó®…®†®‡Ãô®ˆ®‰®Š®‹®Œ®®ŽÃõ®®®‘®’Ãö®“®”®•®–®—®˜"
				+ "Ã÷Ãø®™®šÃù®›®œ®Ãú®ž®Ÿ® ¯A¯B¯C¯DÃûÃü¯EÃý¯FÃþ¯G¯H¯I¯J¯K¯L"
				+ "¯M¯N¯O¯P¯Q¯R¯S¯T¯U¯V¯W¯X¯Y¯Z¯a¯b¯c¯d¯e¯f¯g¯h¯i¯j¯k¯l¯m¯n"
				+ "Ä¡Ä¢¯o¯pÄ£¯q¯rÄ¤Ä¥Ä¦¯s¯t¯u¯v¯w¯xÄ§Ä¨¯yÄ©¯zÄª¯¯‚¯ƒ¯„¯…¯†"
				+ "Ä«Ä¬¯‡¯ˆÄ­¯‰¯Š¯‹Ä®¯Œ¯¯Ž¯¯¯‘¯’Ä¯Ä°¯“Ä±¯”Ä²¯•¯–¯—¯˜¯™¯š"
				+ "Ä³Ä´¯›¯œÄµ¯¯ž¯ŸÄ¶¯ °A°B°C°D°E°FÄ·Ä¸°GÄ¹ÄºÄ»°H°I°J°K°L°M"
				+ "Ä¼Ä½°N°O°P°Q°R°S°T°U°V°W°X°Y°Z°a°b°c°d°e°fÄ¾°g°h°i°j°k°l"
				+ "°m°n°o°p°q°r°s°t°u°v°w°x°y°z°°‚°ƒ°„°…°†°‡°ˆ°‰°Š°‹°Œ°°Ž"
				+ "Ä¿ÄÀ°°ÄÁ°‘°’ÄÂÄÃ°“°”°•°–°—°˜°™ÄÄÄÅ°šÄÆÄÇÄÈ°›°œ°°ž°Ÿ° "
				+ "ÄÉÄÊ±A±BÄË±C±D±EÄÌ±F±G±H±I±J±K±LÄÍÄÎ±MÄÏ±NÄÐ±O±P±Q±R±S±T"
				+ "ÄÑ±U±V±WÄÒ±X±Y±ZÄÓ±a±b±c±d±e±f±gÄÔÄÕ±hÄÖÄ×ÄØ±i±j±k±l±m±n"
				+ "ÄÙ±o±p±q±r±s±t±u±v±w±x±y±z±±‚±ƒ±„±…±†±‡±ˆ±‰±Š±‹±Œ±±Ž±"
				+ "ÄÚÄÛ±±‘ÄÜ±’±“±”ÄÝ±•±–±—±˜±™±š±›ÄÞÄß±œÄà±Äá±ž±Ÿ± ²A²B²C"
				+ "ÄâÄã²D²EÄä²F²G²HÄå²I²J²K²L²M²N²OÄæ²P²Q²R²SÄç²T²U²V²W²X²Y"
				+ "Äè²Z²a²b²c²d²e²f²g²h²i²j²k²l²m²n²o²p²q²r²sÄé²t²u²v²w²x²y"
				+ "Äê²z²²‚²ƒ²„²…²†Äë²‡²ˆ²‰²Š²‹²Œ²²Ž²²²‘²’²“²”²•²–²—²˜²™"
				+ "Äì²š²›²œ²²ž²Ÿ² ³A³B³C³D³E³F³G³H³I³J³K³L³M³N³O³P³Q³R³S³T"
				+ "ÄíÄî³U³VÄï³W³X³YÄð³Z³a³b³c³d³e³fÄñÄò³gÄó³hÄô³i³j³k³l³m³n"
				+ "Äõ³o³p³qÄö³r³s³tÄ÷³u³v³w³x³y³z³³‚³ƒ³„³…³†Äø³‡³ˆ³‰³Š³‹³Œ"
				+ "Äù³³Ž³³³‘³’³“³”³•³–³—³˜³™³š³›³œ³³ž³Ÿ³ Äú´A´B´C´D´E´F"
				+ "ÄûÄü´G´HÄý´I´J´KÄþ´L´M´N´O´P´Q´RÅ¡Å¢´SÅ£´TÅ¤´U´V´W´X´Y´Z"
				+ "Å¥´a´b´cÅ¦´d´e´fÅ§´g´h´i´j´k´l´mÅ¨´n´o´p´q´r´s´t´u´v´w´x"
				+ "Å©Åª´y´zÅ«´´‚´ƒÅ¬´„´…´†´‡´ˆ´‰´ŠÅ­Å®´‹´Œ´Å¯´Ž´´´‘´’´“"
				+ "´”´•´–´—´˜´™´š´›´œ´´ž´Ÿ´ µAµBµCµDµEµFµGµHµIµJµKµLµMµNµO"
				+ "Å°Å±µPµQÅ²µRµSµTÅ³µUµVµWµXµYµZµaÅ´ÅµµbÅ¶µcÅ·µdµeµfµgµhµi"
				+ "Å¸Å¹µjµkÅºµlµmµnÅ»Å¼µoµpµqµrµsµtÅ½Å¾µuÅ¿ÅÀÅÁµvµwµxµyµzµ"
				+ "ÅÂÅÃµ‚µƒÅÄµ„µ…µ†ÅÅµ‡µˆµ‰µŠµ‹µŒµÅÆÅÇµŽÅÈÅÉÅÊµµµ‘µ’µ“µ”"
				+ "ÅËµ•µ–µ—µ˜µ™µšµ›µœµµžµŸµ ¶A¶B¶C¶D¶E¶F¶G¶HÅÌ¶I¶J¶K¶L¶M¶N"
				+ "¶O¶P¶Q¶R¶S¶T¶U¶V¶W¶X¶Y¶Z¶a¶b¶c¶d¶e¶f¶g¶h¶i¶j¶k¶l¶m¶n¶o¶p"
				+ "ÅÍÅÎ¶q¶rÅÏ¶s¶t¶uÅÐ¶vÅÑ¶w¶x¶y¶z¶ÅÒÅÓ¶‚ÅÔÅÕÅÖ¶ƒ¶„¶…¶†¶‡¶ˆ"
				+ "Å×ÅØ¶‰¶ŠÅÙ¶‹¶Œ¶ÅÚ¶Ž¶¶¶‘¶’¶“¶”ÅÛÅÜ¶•ÅÝ¶–ÅÞ¶—¶˜¶™¶š¶›¶œ"
				+ "Åß¶¶ž¶ŸÅà¶ ·A·B·C·D·E·F·G·H·I·J·K·L·M·NÅá·O·P·Q·R·S·T·U"
				+ "Åâ·V·W·XÅã·Y·Z·a·b·c·d·e·f·g·h·i·j·k·l·m·n·o·p·q·r·s·t·u"
				+ "ÅäÅå·v·wÅæ·x·y·zÅç··‚·ƒ·„·…·†·‡ÅèÅé·ˆÅê·‰Åë·Š·‹·Œ·Åì·Ž"
				+ "Åí···‘Åî·’·“·”·•·–·—·˜·™·š·›·œ··ž·Ÿ· ¸A¸B¸C¸D¸E¸F¸G¸H"
				+ "Åï¸I¸J¸K¸L¸M¸N¸O¸P¸Q¸R¸S¸T¸U¸V¸W¸X¸Y¸Z¸a¸b¸c¸d¸e¸f¸g¸h¸i"
				+ "Åð¸j¸k¸lÅñ¸m¸n¸o¸p¸q¸r¸s¸t¸u¸v¸w¸x¸y¸zÅò¸Åó¸‚¸ƒ¸„¸…¸†¸‡"
				+ "Åô¸ˆ¸‰¸Š¸‹¸Œ¸¸Ž¸¸¸‘¸’¸“¸”¸•¸–¸—¸˜¸™¸š¸›¸œ¸¸ž¸Ÿ¸ ¹A¹B"
				+ "ÅõÅö¹C¹DÅ÷¹E¹F¹GÅø¹H¹I¹J¹K¹L¹M¹NÅùÅú¹OÅû¹PÅü¹Q¹R¹S¹T¹U¹V"
				+ "Åý¹W¹X¹Y¹Z¹a¹b¹c¹d¹e¹f¹g¹h¹i¹j¹k¹l¹m¹n¹oÅþ¹p¹q¹r¹s¹t¹u¹v"
				+ "Æ¡¹w¹x¹y¹z¹¹‚¹ƒ¹„¹…¹†¹‡¹ˆ¹‰¹Š¹‹¹Œ¹¹Ž¹¹¹‘¹’¹“¹”¹•¹–¹—"
				+ "Æ¢Æ£¹˜¹™Æ¤¹š¹›¹œÆ¥¹¹ž¹Ÿ¹ ºAºBºCÆ¦Æ§ºDºEºFÆ¨ºGºHºIºJºKºL"
				+ "Æ©ºMºNºOÆªºPºQºRÆ«ºSºTºUºVºWºXºYÆ¬ºZºaºbºcÆ­ºdºeºfºgºhºi"
				+ "Æ®Æ¯ºjºkÆ°ºlºmÆ±Æ²ºnÆ³ºoºpºqºrºsÆ´ÆµºtÆ¶ºuºvºwºxºyºzºº‚"
				+ "Æ·ºƒº„º…Æ¸º†º‡ºˆÆ¹º‰ºŠº‹ºŒººŽºÆºÆ»ºº‘º’º“º”º•º–º—º˜º™"
				+ "Æ¼Æ½ºšº›Æ¾ºœººžÆ¿ºŸº »A»B»C»D»EÆÀÆÁ»FÆÂ»GÆÃ»H»I»J»K»L»M"
				+ "ÆÄÆÅÆÆ»NÆÇ»O»P»QÆÈ»RÆÉ»S»T»U»V»WÆÊÆË»XÆÌÆÍÆÎ»Y»Z»aÆÏ»b»c"
				+ "ÆÐÆÑ»d»eÆÒ»f»g»hÆÓ»i»j»k»l»m»n»oÆÔÆÕ»pÆÖÆ×ÆØ»q»r»s»t»u»v"
				+ "ÆÙÆÚ»w»x»y»z»»‚»ƒ»„»…»†»‡»ˆ»‰»Š»‹»Œ»»Ž»»»‘»’»“»”»•»–"
				+ "»—»˜»™»š»›»œ»»ž»Ÿ» ¼A¼B¼C¼D¼E¼F¼G¼H¼I¼J¼K¼L¼M¼N¼O¼P¼Q¼R"
				+ "ÆÛÆÜ¼S¼TÆÝ¼U¼V¼WÆÞ¼X¼Y¼Z¼a¼b¼c¼dÆßÆà¼eÆáÆâÆã¼f¼g¼h¼i¼j¼k"
				+ "ÆäÆå¼l¼mÆæ¼n¼o¼pÆç¼q¼r¼s¼t¼u¼v¼wÆèÆé¼xÆê¼yÆë¼z¼¼‚¼ƒ¼„¼…"
				+ "Æì¼†¼‡¼ˆÆí¼‰¼Š¼‹Æî¼Œ¼¼Ž¼¼¼‘¼’ÆïÆð¼“¼”ÆñÆò¼•¼–¼—¼˜¼™¼š"
				+ "Æó¼›¼œ¼¼ž¼Ÿ¼ ½AÆô½B½C½D½E½F½G½H½IÆõ½JÆö½K½L½M½N½O½P½Q½R"
				+ "Æ÷Æø½S½TÆù½U½V½WÆú½X½Y½Z½a½b½c½dÆûÆü½eÆý½fÆþ½g½h½i½j½k½l"
				+ "Ç¡½m½n½o½p½q½r½s½t½u½v½w½x½y½z½½‚½ƒ½„½…½†Ç¢½‡½ˆ½‰½Š½‹½Œ"
				+ "½½Ž½½½‘½’½“½”½•½–½—½˜½™½š½›½œ½½ž½Ÿ½ ¾A¾B¾C¾D¾E¾F¾G¾H"
				+ "Ç£¾I¾J¾KÇ¤¾L¾M¾N¾O¾P¾Q¾R¾S¾T¾U¾V¾W¾X¾Y¾Z¾a¾b¾c¾d¾e¾f¾g¾h"
				+ "Ç¥¾i¾j¾kÇ¦¾l¾m¾nÇ§¾o¾p¾q¾r¾s¾t¾u¾vÇ¨¾wÇ©¾x¾y¾z¾¾‚¾ƒ¾„¾…"
				+ "ÇªÇ«¾†¾‡Ç¬¾ˆ¾‰Ç­Ç®¾ŠÇ¯¾‹¾Œ¾¾Ž¾Ç°Ç±¾Ç²¾‘Ç³¾’¾“¾”¾•¾–¾—"
				+ "Ç´¾˜¾™¾š¾›¾œ¾¾ž¾Ÿ¾ ¿A¿B¿C¿D¿E¿F¿G¿H¿I¿J¿KÇµ¿L¿M¿N¿O¿P¿Q"
				+ "¿R¿S¿T¿U¿V¿W¿X¿Y¿Z¿a¿b¿c¿d¿e¿f¿g¿h¿i¿j¿k¿l¿m¿n¿o¿p¿q¿r¿s"
				+ "Ç¶¿t¿u¿vÇ·¿w¿x¿yÇ¸¿z¿¿‚¿ƒ¿„¿…¿†Ç¹¿‡¿ˆÇº¿‰¿Š¿‹¿Œ¿¿Ž¿¿"
				+ "Ç»¿‘¿’¿“Ç¼¿”¿•¿–Ç½¿—¿˜¿™¿š¿›¿œ¿Ç¾¿ž¿ŸÇ¿¿ ÇÀÀAÀBÀCÀDÀEÀF"
				+ "ÇÁÀGÀHÀIÇÂÀJÀKÀLÇÃÀMÀNÀOÀPÀQÀRÀSÇÄÇÅÀTÇÆÀUÀVÀWÀXÀYÀZÀaÀb"
				+ "ÀcÀdÀeÀfÀgÀhÀiÀjÀkÀlÀmÀnÀoÀpÀqÀrÀsÀtÀuÀvÀwÀxÀyÀzÀÀ‚ÀƒÀ„"
				+ "ÇÇÇÈÀ…À†ÇÉÀ‡ÀˆÀ‰ÇÊÀŠÀ‹ÀŒÀÀŽÀÀÇËÇÌÀ‘ÇÍÀ’ÇÎÀ“À”À•À–À—À˜"
				+ "ÇÏÇÐÀ™ÀšÇÑÀ›ÀœÀÇÒÀžÀŸÀ ÁAÇÓÁBÁCÇÔÇÕÁDÇÖÁEÇ×ÁFÁGÁHÁIÁJÁK"
				+ "ÇØÇÙÁLÁMÇÚÁNÁOÁPÇÛÁQÁRÁSÁTÁUÁVÁWÇÜÇÝÁXÇÞÇßÇàÁYÁZÁaÁbÁcÁd"
				+ "ÇáÁeÁfÁgÁhÁiÁjÁkÁlÁmÁnÁoÁpÁqÁrÁsÁtÁuÁvÁwÁxÇâÁyÁzÁÁ‚ÁƒÁ„"
				+ "Á…Á†Á‡ÁˆÁ‰ÁŠÁ‹ÁŒÁÁŽÁÁÁ‘Á’Á“Á”Á•Á–Á—Á˜Á™ÁšÁ›ÁœÁÁžÁŸÁ "
				+ "ÇãÇäÂAÂBÇåÂCÂDÂEÇæÂFÇçÂGÂHÂIÂJÂKÇèÇéÂLÇêÂMÇëÂNÂOÂPÂQÂRÂS"
				+ "ÇìÇíÂTÂUÇîÂVÂWÂXÇïÂYÂZÂaÂbÂcÂdÂeÇðÇñÂfÇòÂgÇóÂhÂiÂjÂkÂlÂm"
				+ "ÇôÇõÂnÂoÇöÂpÂqÂrÇ÷ÂsÂtÂuÂvÂwÂxÂyÇøÇùÂzÇúÇûÇüÂÂ‚ÂƒÂ„Â…Â†"
				+ "ÇýÂ‡ÂˆÂ‰ÇþÂŠÂ‹ÂŒÈ¡ÂÂŽÂÂÂ‘Â’Â“Â”È¢Â•Â–Â—Â˜Â™ÂšÂ›ÂœÂÂž"
				+ "È£È¤ÂŸÂ È¥ÃAÃBÃCÈ¦ÃDÃEÃFÃGÈ§ÃHÃIÈ¨È©ÃJÈªÃKÈ«ÃLÃMÃNÈ¬ÃOÃP"
				+ "È­È®ÃQÃRÈ¯ÃSÃTÃUÈ°ÃVÃWÃXÃYÃZÃaÃbÃcÃdÃeÈ±ÃfÈ²ÃgÃhÃiÃjÃkÃl"
				+ "È³È´ÃmÃnÈµÃoÃpÃqÃrÃsÃtÃuÃvÃwÃxÃyÃzÃÃ‚È¶ÃƒÈ·Ã„Ã…Ã†Ã‡ÃˆÃ‰"
				+ "È¸È¹ÃŠÃ‹ÈºÃŒÃÃŽÈ»ÃÃÃ‘Ã’Ã“Ã”Ã•Ã–È¼Ã—È½Ã˜È¾Ã™ÃšÃ›ÃœÃÃž"
				+ "È¿ÃŸÃ ÄAÈÀÄBÄCÄDÈÁÄEÄFÄGÄHÄIÄJÄKÄLÈÂÄMÈÃÄNÄOÄPÄQÄRÄSÄTÄU"
				+ "ÈÄÈÅÄVÄWÈÆÄXÄYÄZÈÇÄaÄbÄcÄdÈÈÄeÄfÈÉÄgÄhÈÊÄiÈËÄjÄkÄlÄmÄnÄo"
				+ "ÈÌÄpÄqÄrÈÍÄsÄtÄuÈÎÄvÄwÄxÄyÄzÄÄ‚ÈÏÄƒÄ„Ä…Ä†ÈÐÄ‡ÄˆÄ‰ÄŠÄ‹ÄŒ"
				+ "ÈÑÈÒÄÄŽÈÓÄÄÄ‘ÈÔÄ’Ä“Ä”Ä•Ä–Ä—Ä˜Ä™ÄšÄ›ÄœÄÈÕÄžÄŸÄ ÅAÅBÅC"
				+ "ÈÖÈ×ÅDÅEÈØÅFÅGÅHÈÙÅIÅJÅKÅLÅMÅNÅOÈÚÈÛÅPÈÜÅQÈÝÅRÅSÅTÅUÅVÅW"
				+ "ÈÞÈßÅXÅYÈàÅZÅaÅbÈáÅcÅdÅeÅfÅgÅhÅiÈâÅjÅkÈãÅlÈäÅmÅnÅoÅpÅqÅr"
				+ "ÈåÈæÅsÅtÈçÅuÈèÈéÈêÈëÅvÅwÅxÅyÅzÅÈìÈíÅ‚ÈîÅƒÈïÅ„Å…Å†ÈðÅ‡Åˆ"
				+ "ÈñÅ‰ÅŠÅ‹ÈòÅŒÅÅŽÈóÅÅÅ‘Å’Å“Å”Å•ÈôÈõÅ–Å—Å˜ÈöÅ™ÅšÅ›ÅœÅÅž"
				+ "È÷ÈøÅŸÅ ÈùÆAÆBÆCÈúÆDÆEÆFÆGÆHÆIÆJÈûÈüÆKÈýÆLÈþÆMÆNÆOÆPÆQÆR";
		
		String driver = "oracle.jdbc.driver.OracleDriver";
		String url = "jdbc:oracle:thin:@localhost:1521:XE";
		String user = "c##madang";
		String password = "madang";
		Connection conn = null;
		PreparedStatement pstmt = null;
		String sql = "insert into member100 values(?,?,?)";
		Random r = new Random();
		try {
			String id = "";
			String pwd = "";
			String userName = "";
			Class.forName(driver);
			conn = DriverManager.getConnection(url, user, password);
			pstmt = conn.prepareStatement(sql);
			for( int i=200001; i<=1000000; i++) {
				id = "id"+i;
				pwd  = "t"+i;
				userName = firstName [ r.nextInt(firstName.length)]  + name.charAt(r.nextInt(name.length()))  + name.charAt(r.nextInt(name.length()))     ;
				
				pstmt.setString(1, id);
				pstmt.setString(2, pwd);
				pstmt.setString(3, userName);
				pstmt.executeUpdate();
				if(i %1000 == 0) {
					System.out.println(i+"¹øÂ° ·¹ÄÚµå¸¦ Ãß°¡ÇÏ¿´½À´Ï´Ù.");
				}
			}
			
		}catch (Exception e) {
			System.out.println("¿¹¿Ü¹ß»ý:"+e.getMessage());
		}finally {
			try {
				if(pstmt != null) {
					pstmt.close();
				}
				
				if(conn != null) {
					conn.close();
				}
			}catch (Exception e) {
				// TODO: handle exception
			}
		}
		
	}
}
